### ISSUE TITLE
Collision is Wonky

### ISSUE THREAD

**Issue by robtech21** [Alvarito050506/mc4k#2]
I know this technically isn't your fault but is there a way this can be fixed? It kind of sucks getting stuck in the side of blocks when jumping, the cursor sensitivity should be adjusted just a little too. Overall this is a very interesting project, keep up the good work!

**Comment by torralbaa** [comment]
Hello!

> I know this technically isn't your fault but is there a way this can be fixed?

Yup, _technically_ not my fault :P  I'm aware of this issue, currently I'm looking at other Minecraft 4K [mods](https://github.com/search?l=Java&q=minecraft+4k&type=Repositories) and trying to figure out how they handled it.

> the cursor sensitivity should be adjusted just a little too

I know the whole input code is bad or broken, but any specific idea of what you feel is wrong here? I'm guessing less sensitivity near the window borders would fix this. I have also considered locking the mouse, but that would have to be hacky and I'm not sure if it would fit or not.

> Overall this is a very interesting project, keep up the good work!

Thanks! Currently working on some new features!

**Comment by robtech21** [comment]
>I know the whole input code is bad or broken, but any specific idea of what you feel is wrong here? I'm guessing less sensitivity near the window borders would fix this. I have also considered locking the mouse, but that would have to be hacky and I'm not sure if it would fit or not.

Locking the mouse might work, but you would need some way to pause the game so the mouse can unlock itself. Currently, escape just closes the game. Maybe add in a pause menu or something like that? An inventory like the one in MCPI would also be cool.

**Comment by torralbaa** [comment]
> Locking the mouse might work, but you would need some way to pause the game so the mouse can unlock itself. Currently, escape just closes the game. Maybe add in a pause menu or something like that?

Adding a simple menu would be easier than locking the mouse by itself, but I'll work on that.

> An inventory like the one in MCPI would also be cool.

It would be, I would have to extend the "toolkit" a bit though, maybe I'll work on that.

**Comment by robtech21** [comment]
>It would be, I would have to extend the "toolkit" a bit though, maybe I'll work on that.

Alrighty, if you need any help with maybe doing something with the API, I'll be happy to help. :)
